web:
  extends:
    file: docker-compose-common.yml
    service: web
  volumes:
    - ./web:/usr/src/app
  links:
    - postgres:postgres
    - redis:redis
  command: python manage.py runserver 0.0.0.0:8000

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - web:web
  volumes_from:
    - web

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres
  volumes_from:
    - data

redis:
  extends:
    file: docker-compose-common.yml
    service: redis

data:
  extends:
    file: docker-compose-common.yml
    service: data
