web:
  build: web
  expose:
    - "8000"
  ports:
    - "8000:8000"
  env_file: .env
  volumes:
    - ./web/static:/usr/src/app/static

nginx:
  build: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/static:/www/static

postgres:
  image: postgres:9.4.5
  ports:
    - "5432:5432"

redis:
  image: redis:3.0.5
  ports:
    - "6379:6379"

# https://medium.com/@ramangupta/why-docker-data-containers-are-good-589b3c6c749e#.j29ux3f9l
data:
  image: postgres:9.4.5
  volumes:
    - /var/lib/postgresql
  command: "true"
