web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - postgres:postgres
    - redis:redis
  command: gunicorn docker_django.wsgi:application -w 2 -b :8000

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - web:web
  volumes_from:
    - web

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres
  volumes_from:
    - data

redis:
  extends:
    file: docker-compose-common.yml
    service: redis

data:
  extends:
    file: docker-compose-common.yml
    service: data
