
---

- hosts: all
  become: true
  tasks:
    - name: makemigrations
      command: /opt/virtualenvs/roysss/bin/python manage.py makemigrations
      args:
        chdir: /opt/roysss/roysss

    - name: migrate
      command: /opt/virtualenvs/roysss/bin/python manage.py migrate
      args:
        chdir: /opt/roysss/roysss

    - name: Reload roysss service
      command: systemctl daemon-reload

    - name: Restart roysss service
      service: name=roysss state=restarted
