
---

- hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy roysss nginx conf
      copy:
        src: "{{playbook_dir}}/roysss.conf"
        dest: /etc/nginx/sites-enabled
      notify: Reload nginx

    - name: Copy roysss systemd conf
      copy:
        src: "{{playbook_dir}}/roysss.service"
        dest: /etc/systemd/system
        mode: 755
      notify:
        - Enable roysss service
        - Reload roysss service

    - name: Ensure apt cache is up to date
      apt: update_cache=yes

    - name: Install packages
      apt: name={{item}} state=latest
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
        - redis-server
        - python-pip
        - git
        - vim

    - name: Pull git repo
      git:
        repo: https://github.com/cadizm/roysss.git
        dest: /opt/roysss

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: latest

    - name: Make roysss virtualenv
      shell: >
        if [[ ! -d /opt/virtualenvs/roysss ]]; then
          virtualenv /opt/virtualenvs/roysss
        else
          true
        fi

    - name: Install roysss requrements
      pip:
        requirements: /opt/roysss/requirements.txt
        virtualenv: /opt/virtualenvs/roysss

    - name: Copy royss secrets (task)
      command: /bin/true
      notify: Copy roysss secrets

    - name: Set var ownership
      file:
        path: /opt/roysss/var
        owner: www-data
        recurse: yes

    - name: Restart roysss service
      service: name=roysss state=restarted

    - name: Start redis
      service: name=redis-server state=started

  handlers:
    - name: Reload nginx
      service: name=nginx state=reloaded

    - name: Enable roysss service
      service: name=roysss enabled=yes

    - name: Reload roysss service
      command: systemctl daemon-reload

    - name: Copy roysss secrets
      copy:
        src: "{{playbook_dir}}/../roysss/secrets.yml"
        dest: /opt/roysss/roysss/secrets.yml

- include: db.yml
