# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('uuid', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=128)),
                ('address_line1', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=16)),
                ('zipcode', models.CharField(max_length=16)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='shop.Style')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.StripeOrder'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='shop.Item')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Item'),
        ),
    ]
