# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('charge_id', models.CharField(max_length=32)),
                ('stripe_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='shop.StripeOrder')),
            ],
        ),
    ]
